# **Student Productivity Analysis - ETL Pipeline**

* The raw data used in this project was sourced from Kaggle. It no longer appears in my 'viewed' on Kaggle and after a browser issue I don't have the history log to cite the pag URL.

## Objectives

* Load the raw data
* Begin inital checks and cleaning




## Inputs

* Write down which data or information you need to run the notebook 

## Outputs

* Write here which files, code or artefacts you generate by the end of the notebook 

## Additional Comments

* If you have any additional comments that don't fit in the previous bullets, please state them here.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Documents\\vcsode-projects\\Student_Productivity_analysis\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Documents\\vcsode-projects\\Student_Productivity_analysis'

---

# Import libraries & Packages

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

---

# Section 1 - The Extraction

In [5]:
# Load the CSV file 
df_raw = pd.read_csv('Dataset/Raw/Student_Productivity_Dataset.csv')
df_raw.head(10)

,Student_ID,Age,Gender,Study_Hours_Per_Day,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Internet_Quality,Part_Time_Job,Extracurricular_Involvement,AI_Tool_Usage_Hours_Per_Week,Previous_Semester_GPA,Productivity_Score,Performance_Category
0,1,19.0,Male,2.6,5.9,7.4,2.8,86.3,75.1,3.8,2.8,1.4,6.3,Poor,No,4.9,16.4,5.88,51.16,Medium
1,2,25.0,Male,5.4,6.4,6.4,4.1,93.3,99.6,7.9,0.5,8.3,8.2,Good,No,3.9,2.1,6.62,74.10,High
2,3,22.0,Male,6.8,5.5,7.4,4.3,66.3,75.6,4.0,1.7,9.3,4.1,Average,No,4.9,3.6,7.11,34.63,Low
3,4,21.0,Female,1.7,8.0,6.2,2.4,62.8,51.9,3.0,2.5,2.5,10.0,Poor,No,2.8,8.5,6.85,53.20,Medium
4,5,17.0,Male,7.6,6.2,4.3,3.7,87.9,37.0,8.8,3.3,6.1,8.0,Average,No,4.5,5.3,5.86,57.40,Medium
5,6,17.0,Female,3.9,3.0,3.2,2.2,78.0,87.1,2.5,3.9,NaN,1.8,Average,Yes,8.0,2.9,9.83,25.82,Low
6,7,16.0,Male,2.2,10.0,5.3,5.4,91.2,63.2,7.7,NaN,2.6,6.4,NaN,Yes,5.9,4.1,6.83,66.65,High
7,8,23.0,Female,5.7,6.3,4.1,2.4,94.1,65.6,5.2,9.0,1.0,3.3,Poor,No,6.4,3.0,7.62,66.45,High
8,9,21.0,Female,3.3,6.3,5.7,2.6,55.9,94.4,7.5,8.5,5.0,5.8,Poor,No,5.6,2.2,7.84,65.59,High
9,10,22.0,Female,4.0,9.2,4.8,2.2,69.1,72.6,6.6,6.9,5.7,1.0,Good,No,7.9,0.4,5.11,47.47,Medium

In [6]:
# View the basic statistics of the raw dataset
df_raw.describe()

,Student_ID,Age,Study_Hours_Per_Day,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Extracurricular_Involvement,AI_Tool_Usage_Hours_Per_Week,Previous_Semester_GPA,Productivity_Score
count,10000.00000,9845.000000,9835.000000,9894.000000,9868.000000,9920.000000,9878.000000,9882.000000,9815.000000,9863.000000,9846.000000,9825.000000,9822.000000,9860.000000,9839.000000,10000.000000
mean,5000.50000,20.134891,4.219583,6.976602,6.047862,3.032107,79.817301,74.251872,5.991218,3.200862,5.542840,5.957924,4.050204,5.544726,6.489753,54.607333
std,2886.89568,2.497517,1.950639,1.303614,2.424031,1.729774,12.348369,16.588029,2.150297,2.252450,2.107599,2.111982,2.367947,3.892723,1.580462,12.340640
min,1.00000,16.000000,0.000000,3.000000,1.000000,0.000000,40.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2500.75000,18.000000,2.800000,6.100000,4.300000,1.800000,71.200000,62.900000,4.500000,1.600000,4.100000,4.500000,2.300000,2.700000,5.415000,46.640000
50%,5000.50000,20.000000,4.200000,7.000000,6.000000,3.000000,80.200000,74.900000,6.000000,2.700000,5.600000,6.000000,4.000000,4.700000,6.500000,54.935000
75%,7500.25000,22.000000,5.600000,7.900000,7.700000,4.200000,89.100000,86.800000,7.500000,4.300000,7.000000,7.400000,5.700000,7.500000,7.590000,63.032500
max,10000.00000,25.000000,12.000000,10.000000,14.800000,9.700000,100.000000,100.000000,10.000000,15.000000,10.000000,10.000000,10.000000,25.000000,10.000000,100.000000

In [7]:
# Checking the Columns datatypes and non-null counts
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Student_ID                        10000 non-null  int64
 1   Age                               9845 non-null   float64
 2   Gender                            9881 non-null   object
 3   Study_Hours_Per_Day               9835 non-null   float64
 4   Sleep_Hours_Per_Night             9894 non-null   float64
 5   Screen_Time_Hours                 9868 non-null   float64
 6   Social_Media_Hours                9920 non-null   float64
 7   Attendance_Percentage             9878 non-null   float64
 8   Assignments_Completed             9882 non-null   float64
 9   Class_Participation_Score         9815 non-null   float64
 10  Physical_Activity_Hours_Per_Week  9863 non-null   float64
 11  Stress_Level                      9846 non-null   float64
 12  Motivation_Level                  9825 non-null   float64
 13  Internet_Quality                  9851 non-null   object
 14  Part_Time_Job                     9874 non-null   object
 15  Extracurricular_Involvement       9822 non-null   float64
 16  AI_Tool_Usage_Hours_Per_Week      9860 non-null   float64
 17  Previous_Semester_GPA             9839 non-null   float64
 18  Productivity_Score                10000 non-null  float64
 19  Performance_Category              10000 non-null  object
dtypes: float64(15), int64(1), object(4)
memory usage: 1.5+ MB

In [8]:
# Checking the Unique values of each column
df_raw.nunique()

Student_ID                          10000
Age                                    10
Gender                                  3
Study_Hours_Per_Day                   109
Sleep_Hours_Per_Night                  71
Screen_Time_Hours                     131
Social_Media_Hours                     91
Attendance_Percentage                 558
Assignments_Completed                 725
Class_Participation_Score             101
Physical_Activity_Hours_Per_Week      142
Stress_Level                           91
Motivation_Level                       91
Internet_Quality                        3
Part_Time_Job                           2
Extracurricular_Involvement           101
AI_Tool_Usage_Hours_Per_Week          226
Previous_Semester_GPA                 776
Productivity_Score                   4259
Performance_Category                    3
dtype: int64

In [9]:
# reminder to me this was copilot suggestion
# Checking 'Gender' column, typically only expecting 2 values
print(df_raw['Gender'].value_counts())
print(df_raw['Gender'].unique())

Gender
Male      4686
Female    4584
Other      611
Name: count, dtype: int64
['Male' 'Female' nan 'Other']

Having extracted the raw dataset successfully, the initial inspection shows it is well structured but there is a quite a number of missing values that need to be handled in the transformation stage. The next step will be to clean the missing values to preapre it for analysis.

---

# Section 2 - The Transformation

In [10]:
# Making a copy of the raw dataset to work with for cleaning and transformation
df_clean = df_raw.copy()
df_clean.head(10)

,Student_ID,Age,Gender,Study_Hours_Per_Day,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Internet_Quality,Part_Time_Job,Extracurricular_Involvement,AI_Tool_Usage_Hours_Per_Week,Previous_Semester_GPA,Productivity_Score,Performance_Category
0,1,19.0,Male,2.6,5.9,7.4,2.8,86.3,75.1,3.8,2.8,1.4,6.3,Poor,No,4.9,16.4,5.88,51.16,Medium
1,2,25.0,Male,5.4,6.4,6.4,4.1,93.3,99.6,7.9,0.5,8.3,8.2,Good,No,3.9,2.1,6.62,74.10,High
2,3,22.0,Male,6.8,5.5,7.4,4.3,66.3,75.6,4.0,1.7,9.3,4.1,Average,No,4.9,3.6,7.11,34.63,Low
3,4,21.0,Female,1.7,8.0,6.2,2.4,62.8,51.9,3.0,2.5,2.5,10.0,Poor,No,2.8,8.5,6.85,53.20,Medium
4,5,17.0,Male,7.6,6.2,4.3,3.7,87.9,37.0,8.8,3.3,6.1,8.0,Average,No,4.5,5.3,5.86,57.40,Medium
5,6,17.0,Female,3.9,3.0,3.2,2.2,78.0,87.1,2.5,3.9,NaN,1.8,Average,Yes,8.0,2.9,9.83,25.82,Low
6,7,16.0,Male,2.2,10.0,5.3,5.4,91.2,63.2,7.7,NaN,2.6,6.4,NaN,Yes,5.9,4.1,6.83,66.65,High
7,8,23.0,Female,5.7,6.3,4.1,2.4,94.1,65.6,5.2,9.0,1.0,3.3,Poor,No,6.4,3.0,7.62,66.45,High
8,9,21.0,Female,3.3,6.3,5.7,2.6,55.9,94.4,7.5,8.5,5.0,5.8,Poor,No,5.6,2.2,7.84,65.59,High
9,10,22.0,Female,4.0,9.2,4.8,2.2,69.1,72.6,6.6,6.9,5.7,1.0,Good,No,7.9,0.4,5.11,47.47,Medium

In [11]:
# Checking for the total number of null values in each column of the cleaned dataset
df_clean.isnull().sum()

Student_ID                            0
Age                                 155
Gender                              119
Study_Hours_Per_Day                 165
Sleep_Hours_Per_Night               106
Screen_Time_Hours                   132
Social_Media_Hours                   80
Attendance_Percentage               122
Assignments_Completed               118
Class_Participation_Score           185
Physical_Activity_Hours_Per_Week    137
Stress_Level                        154
Motivation_Level                    175
Internet_Quality                    149
Part_Time_Job                       126
Extracurricular_Involvement         178
AI_Tool_Usage_Hours_Per_Week        140
Previous_Semester_GPA               161
Productivity_Score                    0
Performance_Category                  0
dtype: int64

In [12]:
# Double checking for any duplicate rows
df_clean.duplicated().sum()

0

In [13]:
# Firstly I need to clean the Gender column
# I will drop all 'NaN' and 'Other' values in the Gender column
df_clean = df_clean[df_clean['Gender'].isin(['Male', 'Female'])]
df_clean

,Student_ID,Age,Gender,Study_Hours_Per_Day,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Internet_Quality,Part_Time_Job,Extracurricular_Involvement,AI_Tool_Usage_Hours_Per_Week,Previous_Semester_GPA,Productivity_Score,Performance_Category
0,1,19.0,Male,2.6,5.9,7.4,2.8,86.3,75.1,3.8,2.8,1.4,6.3,Poor,No,4.9,16.4,5.88,51.16,Medium
1,2,25.0,Male,5.4,6.4,6.4,4.1,93.3,99.6,7.9,0.5,8.3,8.2,Good,No,3.9,2.1,6.62,74.10,High
2,3,22.0,Male,6.8,5.5,7.4,4.3,66.3,75.6,4.0,1.7,9.3,4.1,Average,No,4.9,3.6,7.11,34.63,Low
3,4,21.0,Female,1.7,8.0,6.2,2.4,62.8,51.9,3.0,2.5,2.5,10.0,Poor,No,2.8,8.5,6.85,53.20,Medium
4,5,17.0,Male,7.6,6.2,4.3,3.7,87.9,37.0,8.8,3.3,6.1,8.0,Average,No,4.5,5.3,5.86,57.40,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,23.0,Female,4.2,5.5,5.2,1.6,95.5,100.0,6.6,5.0,7.7,8.5,Average,No,9.0,6.3,6.51,80.59,High
9996,9997,24.0,Male,7.1,6.7,4.0,3.2,64.3,74.5,4.0,0.5,6.8,9.4,Good,Yes,7.0,7.1,6.97,62.95,Medium
9997,9998,24.0,Male,6.4,4.4,6.7,3.3,74.1,100.0,10.0,4.5,5.4,1.0,Average,No,0.0,8.2,1.80,43.79,Low
9998,9999,19.0,Male,8.1,6.8,3.5,4.1,59.5,85.9,7.2,4.6,5.0,5.8,Poor,Yes,4.1,3.5,5.24,49.48,Medium
9999,10000,18.0,Male,4.6,7.2,6.8,3.1,66.0,32.1,7.4,2.3,6.4,9.2,Good,No,7.2,4.0,5.54,62.81,Medium

In [14]:
# Checking the cleaned Gender column
print(df_clean['Gender'].value_counts())
print(df_clean['Gender'].unique())

Gender
Male      4686
Female    4584
Name: count, dtype: int64
['Male' 'Female']

In [15]:
# Replace all missing values in the Sleep_Hours_Per_Night column
df_clean['Sleep_Hours_Per_Night'] = df_clean['Sleep_Hours_Per_Night'].fillna(df_clean['Sleep_Hours_Per_Night'].mean())
df_clean['Sleep_Hours_Per_Night'].value_counts()  # Check the unique values in the column after filling missing values 

# After viewing the table, I see a result that needs to rounded to 1 decimal place
df_clean['Sleep_Hours_Per_Night'] = df_clean['Sleep_Hours_Per_Night'].round(1)
df_clean['Sleep_Hours_Per_Night'].value_counts()

Sleep_Hours_Per_Night
7.0    375
7.2    303
6.9    302
7.1    285
6.6    266
      ...
3.6      9
3.2      8
3.4      6
3.1      2
3.3      1
Name: count, Length: 71, dtype: int64

In [16]:
# Do the same for the remaining numerical columns 
numeric_cols = [
    'Screen_Time_Hours',
    'Social_Media_Hours',
    'Physical_Activity_Hours_Per_Week',
    'Previous_Semester_GPA',
    'Productivity_Score',
    'Attendance_Percentage',
    'Assignments_Completed',
    'Class_Participation_Score',
    'Stress_Level',
    'Motivation_Level',
    'Previous_Semester_GPA'
    
]
for col in numeric_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].mean()).round(1)

df_clean[numeric_cols].isnull().sum()  # Confirm their is no more missing values in the numerical columns

Screen_Time_Hours                   0
Social_Media_Hours                  0
Physical_Activity_Hours_Per_Week    0
Previous_Semester_GPA               0
Productivity_Score                  0
Attendance_Percentage               0
Assignments_Completed               0
Class_Participation_Score           0
Stress_Level                        0
Motivation_Level                    0
Previous_Semester_GPA               0
dtype: int64

In [17]:
# Dropping columns not needed for analysis
drop_columns = ['Student_ID', 'Age', 'Study_Hours_Per_Day', 'Internet_Quality', 'Part_Time_Job', 'AI_Tool_Usage_Hours_Per_Week']
df_clean = df_clean.drop(columns=drop_columns)
df_clean

,Gender,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Extracurricular_Involvement,Previous_Semester_GPA,Productivity_Score,Performance_Category
0,Male,5.9,7.4,2.8,86.3,75.1,3.8,2.8,1.4,6.3,4.9,5.9,51.2,Medium
1,Male,6.4,6.4,4.1,93.3,99.6,7.9,0.5,8.3,8.2,3.9,6.6,74.1,High
2,Male,5.5,7.4,4.3,66.3,75.6,4.0,1.7,9.3,4.1,4.9,7.1,34.6,Low
3,Female,8.0,6.2,2.4,62.8,51.9,3.0,2.5,2.5,10.0,2.8,6.8,53.2,Medium
4,Male,6.2,4.3,3.7,87.9,37.0,8.8,3.3,6.1,8.0,4.5,5.9,57.4,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,5.5,5.2,1.6,95.5,100.0,6.6,5.0,7.7,8.5,9.0,6.5,80.6,High
9996,Male,6.7,4.0,3.2,64.3,74.5,4.0,0.5,6.8,9.4,7.0,7.0,63.0,Medium
9997,Male,4.4,6.7,3.3,74.1,100.0,10.0,4.5,5.4,1.0,0.0,1.8,43.8,Low
9998,Male,6.8,3.5,4.1,59.5,85.9,7.2,4.6,5.0,5.8,4.1,5.2,49.5,Medium
9999,Male,7.2,6.8,3.1,66.0,32.1,7.4,2.3,6.4,9.2,7.2,5.5,62.8,Medium

With the data cleaned, I'll now begin feature engineering for the analysis.

In [18]:
# Start with encoding the Gender column

df_clean['Gender_Encoded'] = df_clean['Gender'].map({'Female': 0, 'Male': 1})
df_clean

,Gender,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Extracurricular_Involvement,Previous_Semester_GPA,Productivity_Score,Performance_Category,Gender_Encoded
0,Male,5.9,7.4,2.8,86.3,75.1,3.8,2.8,1.4,6.3,4.9,5.9,51.2,Medium,1
1,Male,6.4,6.4,4.1,93.3,99.6,7.9,0.5,8.3,8.2,3.9,6.6,74.1,High,1
2,Male,5.5,7.4,4.3,66.3,75.6,4.0,1.7,9.3,4.1,4.9,7.1,34.6,Low,1
3,Female,8.0,6.2,2.4,62.8,51.9,3.0,2.5,2.5,10.0,2.8,6.8,53.2,Medium,0
4,Male,6.2,4.3,3.7,87.9,37.0,8.8,3.3,6.1,8.0,4.5,5.9,57.4,Medium,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,5.5,5.2,1.6,95.5,100.0,6.6,5.0,7.7,8.5,9.0,6.5,80.6,High,0
9996,Male,6.7,4.0,3.2,64.3,74.5,4.0,0.5,6.8,9.4,7.0,7.0,63.0,Medium,1
9997,Male,4.4,6.7,3.3,74.1,100.0,10.0,4.5,5.4,1.0,0.0,1.8,43.8,Low,1
9998,Male,6.8,3.5,4.1,59.5,85.9,7.2,4.6,5.0,5.8,4.1,5.2,49.5,Medium,1
9999,Male,7.2,6.8,3.1,66.0,32.1,7.4,2.3,6.4,9.2,7.2,5.5,62.8,Medium,1

In [19]:
# Encoding categories for 'Sleep_Hours_Per_Night'

def Sleep_Quality(Hours):
    if Hours <= 6.9:
        return 'Poor'
    elif Hours > 6.9 and Hours <= 8:
        return 'Healthy'
    else:
        return 'Excessive'

df_clean['Sleep_Hours_Per_Night'] = df_clean['Sleep_Hours_Per_Night'].apply(Sleep_Quality) 
df_clean.head(10)

,Gender,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Extracurricular_Involvement,Previous_Semester_GPA,Productivity_Score,Performance_Category,Gender_Encoded
0,Male,Poor,7.4,2.8,86.3,75.1,3.8,2.8,1.4,6.3,4.9,5.9,51.2,Medium,1
1,Male,Poor,6.4,4.1,93.3,99.6,7.9,0.5,8.3,8.2,3.9,6.6,74.1,High,1
2,Male,Poor,7.4,4.3,66.3,75.6,4.0,1.7,9.3,4.1,4.9,7.1,34.6,Low,1
3,Female,Healthy,6.2,2.4,62.8,51.9,3.0,2.5,2.5,10.0,2.8,6.8,53.2,Medium,0
4,Male,Poor,4.3,3.7,87.9,37.0,8.8,3.3,6.1,8.0,4.5,5.9,57.4,Medium,1
5,Female,Poor,3.2,2.2,78.0,87.1,2.5,3.9,5.5,1.8,8.0,9.8,25.8,Low,0
6,Male,Excessive,5.3,5.4,91.2,63.2,7.7,3.2,2.6,6.4,5.9,6.8,66.6,High,1
7,Female,Poor,4.1,2.4,94.1,65.6,5.2,9.0,1.0,3.3,6.4,7.6,66.4,High,0
8,Female,Poor,5.7,2.6,55.9,94.4,7.5,8.5,5.0,5.8,5.6,7.8,65.6,High,0
9,Female,Excessive,4.8,2.2,69.1,72.6,6.6,6.9,5.7,1.0,7.9,5.1,47.5,Medium,0

In [ ]:
# Encoding Screen time hours
# Assumed that this value is daily, not weekly

def Daily_Screen_Time(Hours):
    if Hours <= 2:
        return 'Low'
    elif Hours > 2 and Hours <= 4:
        return 'Moderate'
    else:
        return 'High'

df_clean['Screen_Time_Hours'] = df_clean['Screen_Time_Hours'].apply(Daily_Screen_Time)
df_clean.head(10)

,Gender,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Extracurricular_Involvement,Previous_Semester_GPA,Productivity_Score,Performance_Category,Gender_Encoded
0,Male,Poor,High,2.8,86.3,75.1,3.8,2.8,1.4,6.3,4.9,5.9,51.2,Medium,1
1,Male,Poor,High,4.1,93.3,99.6,7.9,0.5,8.3,8.2,3.9,6.6,74.1,High,1
2,Male,Poor,High,4.3,66.3,75.6,4.0,1.7,9.3,4.1,4.9,7.1,34.6,Low,1
3,Female,Healthy,High,2.4,62.8,51.9,3.0,2.5,2.5,10.0,2.8,6.8,53.2,Medium,0
4,Male,Poor,High,3.7,87.9,37.0,8.8,3.3,6.1,8.0,4.5,5.9,57.4,Medium,1
5,Female,Poor,Moderate,2.2,78.0,87.1,2.5,3.9,5.5,1.8,8.0,9.8,25.8,Low,0
6,Male,Excessive,High,5.4,91.2,63.2,7.7,3.2,2.6,6.4,5.9,6.8,66.6,High,1
7,Female,Poor,High,2.4,94.1,65.6,5.2,9.0,1.0,3.3,6.4,7.6,66.4,High,0
8,Female,Poor,High,2.6,55.9,94.4,7.5,8.5,5.0,5.8,5.6,7.8,65.6,High,0
9,Female,Excessive,High,2.2,69.1,72.6,6.6,6.9,5.7,1.0,7.9,5.1,47.5,Medium,0

In [21]:
# Encoding Social Media Hours
# Also assumed that this value is daily

def Daily_Social_Media_Time(Hours):
    if Hours <= 1:
        return 'Low'
    elif Hours > 1 and Hours <= 2:
        return 'Moderate'
    else:
        return 'High'  

df_clean['Social_Media_Hours'] = df_clean['Social_Media_Hours'].apply(Daily_Social_Media_Time)
df_clean.head(10)

,Gender,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Extracurricular_Involvement,Previous_Semester_GPA,Productivity_Score,Performance_Category,Gender_Encoded
0,Male,Poor,High,High,86.3,75.1,3.8,2.8,1.4,6.3,4.9,5.9,51.2,Medium,1
1,Male,Poor,High,High,93.3,99.6,7.9,0.5,8.3,8.2,3.9,6.6,74.1,High,1
2,Male,Poor,High,High,66.3,75.6,4.0,1.7,9.3,4.1,4.9,7.1,34.6,Low,1
3,Female,Healthy,High,High,62.8,51.9,3.0,2.5,2.5,10.0,2.8,6.8,53.2,Medium,0
4,Male,Poor,High,High,87.9,37.0,8.8,3.3,6.1,8.0,4.5,5.9,57.4,Medium,1
5,Female,Poor,Moderate,High,78.0,87.1,2.5,3.9,5.5,1.8,8.0,9.8,25.8,Low,0
6,Male,Excessive,High,High,91.2,63.2,7.7,3.2,2.6,6.4,5.9,6.8,66.6,High,1
7,Female,Poor,High,High,94.1,65.6,5.2,9.0,1.0,3.3,6.4,7.6,66.4,High,0
8,Female,Poor,High,High,55.9,94.4,7.5,8.5,5.0,5.8,5.6,7.8,65.6,High,0
9,Female,Excessive,High,High,69.1,72.6,6.6,6.9,5.7,1.0,7.9,5.1,47.5,Medium,0

In [22]:
# Encoding physical activity hours per week
# NHS recommends at least 2.5 hours of exercise per week
# I will use that as a benchmark for the categories

def Weekly_Physical_Activity(Hours):
    if Hours <= 2:
        return 'Underactive'
    elif Hours > 2 and Hours <= 3:
        return 'Moderately Active'
    else:
        return 'Very Active'

df_clean['Physical_Activity_Hours_Per_Week'] = df_clean['Physical_Activity_Hours_Per_Week'].apply(Weekly_Physical_Activity)
df_clean.head(10)

,Gender,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Extracurricular_Involvement,Previous_Semester_GPA,Productivity_Score,Performance_Category,Gender_Encoded
0,Male,Poor,High,High,86.3,75.1,3.8,Moderately Active,1.4,6.3,4.9,5.9,51.2,Medium,1
1,Male,Poor,High,High,93.3,99.6,7.9,Underactive,8.3,8.2,3.9,6.6,74.1,High,1
2,Male,Poor,High,High,66.3,75.6,4.0,Underactive,9.3,4.1,4.9,7.1,34.6,Low,1
3,Female,Healthy,High,High,62.8,51.9,3.0,Moderately Active,2.5,10.0,2.8,6.8,53.2,Medium,0
4,Male,Poor,High,High,87.9,37.0,8.8,Very Active,6.1,8.0,4.5,5.9,57.4,Medium,1
5,Female,Poor,Moderate,High,78.0,87.1,2.5,Very Active,5.5,1.8,8.0,9.8,25.8,Low,0
6,Male,Excessive,High,High,91.2,63.2,7.7,Very Active,2.6,6.4,5.9,6.8,66.6,High,1
7,Female,Poor,High,High,94.1,65.6,5.2,Very Active,1.0,3.3,6.4,7.6,66.4,High,0
8,Female,Poor,High,High,55.9,94.4,7.5,Very Active,5.0,5.8,5.6,7.8,65.6,High,0
9,Female,Excessive,High,High,69.1,72.6,6.6,Very Active,5.7,1.0,7.9,5.1,47.5,Medium,0

---

NOTE

* You may add as many sections as you want, as long as it supports your project workflow.
* All notebook's cells should be run top-down (you can't create a dynamic wherein a given point you need to go back to a previous cell to execute some task, like go back to a previous cell and refresh a variable content)

---

# Conclusions and Next Steps

* In cases where you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.